[package]
name = "gh"
version = "0.2.0"
authors = ["Michael Klishin <michael@clojurewerkz.org>"]

[dependencies]

reqwest = "0.9"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

rand = "0.6"

failure = "0.1"
failure_derive = "0.1"
