[package]
name = "gh"
version = "0.1.0"
authors = ["Michael Klishin <michael@clojurewerkz.org>"]

[dependencies]

reqwest = "0.8.5"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

rand = "0.4"

failure = "0.1"
failure_derive = "0.1"
